export const LaplacianFilter = [
  0.0, -1.0, 0.0, -1.0, 4.0, -1.0, 0.0, -1.0, 0.0,
];
export const GaussianKernel = [
  1 / 16,
  1 / 8,
  1 / 16,
  1 / 8,
  1 / 4,
  1 / 8,
  1 / 16,
  1 / 8,
  1 / 16,
];
export const BoxFilter = [
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
];

export const MeasureHeader = [
  '',
  'Pixels in Area',
  'X Center of Gravity',
  'Y Center of Gravity',
  'Min X in Area',
  'Max X in Area',
  'Min Y in Area',
  'Max Y in Area',
  'Area Width',
  'Area Height',
  '0 Degree Direction Length',
  '11.25 Degree Direction Length',
  '22.5 Degree Direction Length',
  '33.75 Degree Direction Length',
  '45 Degree Direction Length',
  '56.25 Degree Direction Length',
  '67.5 Degree Direction Length',
  '78.75 Degree Direction Length',
  '90 Degree Direction Length',
  '101.25 Degree Direction Length',
  '112.5 Degree Direction Length',
  '123.75 Degree Direction Length',
  '135 Degree Direction Length',
  '146.25 Degree Direction Length',
  '157.5 Degree Direction Length',
  '168.75 Degree Direction Length',
  '10000 Parts of Count (Count/Total Pixels)',
  'Center of Gravity X/Width (10000 Points)',
  'Center of Gravity Y/Height (10000 Points)',
  'Xmin/Wdith (10000 Points)',
  'Xmax/Width (10000 Points)',
  'Ymin/Height (10000 Points)',
  'Ymax/Height (10000 Points)',
  'Towel/Width (10000 Points)',
  'Height/Height (10000 Minutes)',
  '',
  '',
  '',
  '',
  '',
  'Inverse Flattening Rate',
  'Short Side Length',
  'Long Side Length',
  'Flatness, 10000 fractions',
  'Roundness, 10000 minutes',
  'Ellipsity, 10000 parts',
  'Four-Angle, 10000 points',
  'Round: Outer Perimeter',
  'Average Thickness',
  'Slender Length',
  'Wrap count',
  '100 Times the Outer Area Ratio',
  'Short Side Orientation',
  'Long Side Orientation',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Internal Average Value',
  'internal Maximum',
  'Internal Minimum',
  'Internal Maximum Contrast',
  'External Average Value',
  'External Maximum',
  'External Minimum',
  'External Maximum Contrast',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Sort by Size and Circularity',
  'Sorted by Contrast and Circularity',
  'Internal Selected by Size and Contrast',
  'External Selected by Size and Contrast',
];
