export const LaplacianFilter = [
  0.0, -1.0, 0.0, -1.0, 4.0, -1.0, 0.0, -1.0, 0.0,
];
export const GaussianKernel = [
  1 / 16,
  1 / 8,
  1 / 16,
  1 / 8,
  1 / 4,
  1 / 8,
  1 / 16,
  1 / 8,
  1 / 16,
];
export const BoxFilter = [
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
  1 / 9,
];

export const MeasureHeader = [
  '',
  'Pixels in Area',
  'X Center of Gravity',
  'Y Center of Gravity',
  'Min X in Area',
  'Max X in Area',
  'Min Y in Area',
  'Max Y in Area',
  'Area Width',
  'Area Height',
  'Inverse Flattening Rate',
  'Short Side Length',
  'Long Side Length',
  'Oblateness',
  'Roundness',
  'Ellipsity',
  'Rectangular Filling Ratio',
  'Outer Pixels',
  'Average Thickness',
  'Slenderness',
  'Wrap count',
  'Outer Area',
  'Degree of Short Side Direction',
  'Degree of Long Side Direction',
  'Average Pixel Value of Area',
  'Minimum Pixel Value of Area',
  'Maximum Pixel Value of Area',
  'Internal Contrast',
  'Average Pixel Value of External Area',
  'Contrast of Inner & External Area',
  'Internal Contrast',
];
